"use client";

import { FormEvent } from "react";
import { X } from "lucide-react";
import { DOCUMENT_TYPES, type DocumentType } from "@/lib/document-types";
import type { EntryForm, Partner } from "@/types/accounting";

export function EntryDrawer(props: { open: boolean; title: "KUF" | "KIF"; form: EntryForm; setForm: (form: EntryForm) => void; partnerSearch: string; setPartnerSearch: (value: string) => void; partners: Partner[]; editing: boolean; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  if (!props.open) return null;
  const listId = `${props.title.toLowerCase()}-drawer-partners`;
  return <div className="drawer-layer"><button className="drawer-backdrop" aria-label="Zatvori formu" onClick={props.onClose} /><aside className="drawer" aria-label={`${props.title} forma`}><div className="drawer-header"><div><span className="eyebrow">{props.editing ? "Izmjena stavke" : "Nova stavka"}</span><h2>{props.title} faktura</h2></div><button className="icon-button" aria-label="Zatvori" onClick={props.onClose}><X size={20} /></button></div><form className="drawer-form" onSubmit={props.onSubmit}><label><span>Partner</span><input list={listId} placeholder="Počnite unositi naziv partnera" value={props.partnerSearch} onChange={(event) => { const value = event.target.value; props.setPartnerSearch(value); props.setForm({ ...props.form, partnerId: props.partners.find((partner) => partner.name === value)?.id ?? "" }); }} required /></label><datalist id={listId}>{props.partners.map((partner) => <option key={partner.id} value={partner.name}>{partner.vat_number}</option>)}</datalist><div className="form-row"><label><span>Tip dokumenta</span><select value={props.form.documentType} onChange={(event) => props.setForm({ ...props.form, documentType: event.target.value as DocumentType })}>{DOCUMENT_TYPES.map((type) => <option key={type} value={type}>Tip {type}</option>)}</select></label><label><span>Broj fakture</span><input placeholder="npr. 2026-001" value={props.form.invoiceNumber} onChange={(event) => props.setForm({ ...props.form, invoiceNumber: event.target.value })} required /></label></div><div className="form-row"><label><span>Datum fakture</span><input type="date" value={props.form.invoiceDate} onChange={(event) => props.setForm({ ...props.form, invoiceDate: event.target.value })} required /></label><label><span>Ukupan iznos</span><div className="amount-input"><input type="number" step="0.01" min="0" placeholder="0.00" value={props.form.amount} onChange={(event) => props.setForm({ ...props.form, amount: event.target.value })} required /><span>KM</span></div></label></div><div className="drawer-note">Stavka će biti spremljena u aktivnu firmu i porezni period.</div><div className="drawer-actions"><button type="button" className="button secondary" onClick={props.onClose}>Odustani</button><button className="button primary">{props.editing ? "Sačuvaj izmjene" : "Dodaj stavku"}</button></div></form></aside></div>;
}
