"use client";

import { useMemo, useState } from "react";
import { Building2, Plus, Search, X } from "lucide-react";
import { emptyPartner, type Partner, type PartnerForm } from "@/types/accounting";

export function PartnersView(props: { partners: Partner[]; onCreate: (partner: PartnerForm) => Promise<boolean> }) {
  const [query, setQuery] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [form, setForm] = useState<PartnerForm>(emptyPartner());
  const visiblePartners = useMemo(() => props.partners.filter((partner) => `${partner.name} ${partner.vat_number ?? ""} ${partner.jib ?? ""}`.toLowerCase().includes(query.toLowerCase())), [props.partners, query]);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (await props.onCreate(form)) { setForm(emptyPartner()); setDrawerOpen(false); } }

  return <div className="view-stack"><div className="page-heading"><div><span className="eyebrow">Matični podaci</span><h1>Partneri</h1><p>Kupci i dobavljači aktivne firme</p></div><button className="button primary" onClick={() => setDrawerOpen(true)}><Plus size={18} />Dodaj partnera</button></div>
    <section className="panel table-panel"><div className="table-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Pretraži partnere" placeholder="Pretraži naziv, PDV broj ili JIB..." value={query} onChange={(event) => setQuery(event.target.value)} /></div><span className="toolbar-count">{visiblePartners.length} partnera</span></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Partner</th><th>Adresa</th><th>PDV broj</th><th>JIB</th></tr></thead><tbody>{visiblePartners.length ? visiblePartners.map((partner) => <tr key={partner.id}><td><div className="partner-name"><span><Building2 size={17} /></span><strong>{partner.name}</strong></div></td><td>{partner.address}</td><td><code>{partner.vat_number || "—"}</code></td><td><code>{partner.jib || "—"}</code></td></tr>) : <tr><td colSpan={4}><div className="empty-table"><span className="metric-icon violet"><Building2 size={22} /></span><strong>Nema pronađenih partnera</strong><p>Dodajte prvog kupca ili dobavljača.</p></div></td></tr>}</tbody></table></div></section>
    {drawerOpen && <div className="drawer-layer"><button className="drawer-backdrop" aria-label="Zatvori formu" onClick={() => setDrawerOpen(false)} /><aside className="drawer"><div className="drawer-header"><div><span className="eyebrow">Matični podaci</span><h2>Novi partner</h2></div><button className="icon-button" aria-label="Zatvori" onClick={() => setDrawerOpen(false)}><X size={20} /></button></div><form className="drawer-form" onSubmit={(event) => void submit(event)}><label><span>Naziv partnera</span><input placeholder="Puni poslovni naziv" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label><span>Adresa</span><input placeholder="Ulica, broj i grad" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} required /></label><div className="form-row"><label><span>PDV broj (opcionalno)</span><input inputMode="numeric" placeholder="12 cifara ili prazno" value={form.vatNumber} onChange={(event) => setForm({ ...form, vatNumber: event.target.value })} /></label><label><span>JIB (opcionalno)</span><input inputMode="numeric" placeholder="13 cifara ili prazno" value={form.jib} onChange={(event) => setForm({ ...form, jib: event.target.value })} /></label></div><div className="drawer-note">Za partnera koji nije PDV obveznik identifikatori mogu ostati prazni. Za uvoz ili izvoz unesite 12, odnosno 13 nula.</div><div className="drawer-actions"><button type="button" className="button secondary" onClick={() => setDrawerOpen(false)}>Odustani</button><button className="button primary">Spremi partnera</button></div></form></aside></div>}
  </div>;
}
