"use client";

import { useMemo, useState } from "react";
import { Building2, Plus, Users } from "lucide-react";
import { Button, Drawer, EmptyState, Field, Input, SearchInput, TableToolbar } from "@/components/ui/primitives";
import { emptyPartner, type Partner, type PartnerForm } from "@/types/accounting";

export function PartnersView(props: { partners: Partner[]; onCreate: (partner: PartnerForm) => Promise<boolean> }) {
  const [query, setQuery] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [attempted, setAttempted] = useState(false);
  const [form, setForm] = useState<PartnerForm>(emptyPartner());
  const visiblePartners = useMemo(() => props.partners.filter((partner) => `${partner.name} ${partner.vat_number ?? ""} ${partner.jib ?? ""}`.toLowerCase().includes(query.toLowerCase())), [props.partners, query]);
  const vatError = attempted && form.vatNumber && !/^\d{12}$/.test(form.vatNumber) ? "PDV broj mora imati tačno 12 cifara." : undefined;
  const jibError = attempted && form.jib && !/^\d{13}$/.test(form.jib) ? "JIB mora imati tačno 13 cifara." : undefined;
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setAttempted(true); if ((form.vatNumber && !/^\d{12}$/.test(form.vatNumber)) || (form.jib && !/^\d{13}$/.test(form.jib))) return; if (await props.onCreate(form)) { setForm(emptyPartner()); setAttempted(false); setDrawerOpen(false); } }
  function openDrawer() { setForm(emptyPartner()); setAttempted(false); setDrawerOpen(true); }

  return <div className="view-stack"><div className="page-heading"><div><span className="eyebrow">Matični podaci</span><h1>Partneri</h1><p>Kupci i dobavljači aktivne firme</p></div><Button onClick={openDrawer}><Plus size={17} />Dodaj partnera</Button></div>
    <section className="panel table-panel"><TableToolbar count={`${visiblePartners.length} partnera`}><SearchInput label="Pretraži partnere" placeholder="Naziv, PDV broj ili JIB…" value={query} onChange={setQuery} /></TableToolbar><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Partner</th><th>Adresa</th><th>PDV broj</th><th>JIB</th></tr></thead><tbody>{visiblePartners.length ? visiblePartners.map((partner) => <tr key={partner.id}><td><div className="partner-name"><span><Building2 size={16} /></span><strong>{partner.name}</strong></div></td><td>{partner.address}</td><td><code>{partner.vat_number || "—"}</code></td><td><code>{partner.jib || "—"}</code></td></tr>) : <tr><td colSpan={4}><EmptyState icon={Users} title={query ? "Nema pronađenih partnera" : "Nema partnera"} description={query ? "Provjerite pojam pretrage ili očistite filter." : "Dodajte prvog kupca ili dobavljača aktivne firme."} action={!query ? <Button size="sm" onClick={openDrawer}><Plus size={15} />Dodaj partnera</Button> : undefined} /></td></tr>}</tbody></table></div></section>
    <Drawer open={drawerOpen} title="Novi partner" eyebrow="Matični podaci" onClose={() => setDrawerOpen(false)}><form className="drawer-form" onSubmit={(event) => void submit(event)}><section className="form-group"><div className="form-group-heading"><span>01</span><div><strong>Poslovni podaci</strong><p>Podaci koji se koriste u KUF/KIF evidenciji.</p></div></div><div className="form-group-fields"><Field label="Naziv partnera" required error={attempted && !form.name.trim() ? "Naziv partnera je obavezan." : undefined}><Input placeholder="Puni poslovni naziv" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></Field><Field label="Adresa" required error={attempted && !form.address.trim() ? "Adresa je obavezna." : undefined}><Input placeholder="Ulica, broj i grad" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} required /></Field></div></section><section className="form-group"><div className="form-group-heading"><span>02</span><div><strong>Porezni identifikatori</strong><p>Za neobveznika identifikatori mogu ostati prazni.</p></div></div><div className="form-group-fields form-row"><Field label="PDV broj" helper="12 cifara ili prazno." error={vatError}><Input inputMode="numeric" placeholder="000000000000" value={form.vatNumber} aria-invalid={Boolean(vatError)} onChange={(event) => setForm({ ...form, vatNumber: event.target.value })} /></Field><Field label="JIB" helper="13 cifara ili prazno." error={jibError}><Input inputMode="numeric" placeholder="0000000000000" value={form.jib} aria-invalid={Boolean(jibError)} onChange={(event) => setForm({ ...form, jib: event.target.value })} /></Field></div></section><div className="drawer-note">Za uvoz ili izvoz unesite 12, odnosno 13 nula. Sistem ne dopunjava identifikatore automatski.</div><div className="drawer-actions"><Button type="button" variant="secondary" onClick={() => setDrawerOpen(false)}>Odustani</Button><Button>Spremi partnera</Button></div></form></Drawer>
  </div>;
}
